CREATE TABLE IF NOT EXISTS institution(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50)NOT NULL,
    description TEXT NOT NULL,
    website TEXT NOT NULL,
    owner_id BIGINT REFERENCES users(id) ON DELETE cascade NOT NULL ,
    latitude VARCHAR(50)NOT NULL,
    longitude VARCHAR(50)NOT NULL,
    address VARCHAR(100)NOT NULL,
    phone VARCHAR(12)NOT NULL,
    country VARCHAR(50)NOT NULL,
    city BIGINT REFERENCES city(id)NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

