CREATE TABLE IF NOT EXISTS rating (
    id BIGSERIAL PRIMARY KEY,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE CASCADE UNIQUE NOT NULL,
    service_id BIGINT REFERENCES services(id) ON DELETE CASCADE,
    institution_id BIGINT REFERENCES institution(id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES employee(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 10),
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

