version: '3'

services:


  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      AUTH_SERVICE: "authentication-service:50001"
      STAFF_SERVICE_HOST_WITHSLASHATTHEEND: "staff-service/"
      RABBITMQ_HOST: "amqp://guest:guest@rabbitmq"
      INSTITUTION_SERVICE: "institution-service:50002"


  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "50001:50001"
      - "8090:8090"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      # DSN: "postgres://reservehub:190704Samat@reserve-hub-database.cnwmuwismjtn.us-east-1.rds.amazonaws.com:5432/postgres"
      # REDIS_ADDR: "reserve-hub-cache-redis.owhyr8.clustercfg.use1.cache.amazonaws.com:6379"
      DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
      REDIS_ADDR: "redis:6379"
      SMS_URL: "https://7103.api.greenapi.com/waInstance7103936689/sendMessage/1ff5dea20a3b44448069f001facf63119d2aa20278a344ce9c"
  institution-service:
    build:
      context: ./../institution-service
      dockerfile: ./../institution-service/inst-service.dockerfile
    restart: always
    ports:
      - "8091:8091"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
      AUTH_SERVICE: "authentication-service:50001"

  staff-service:
    build:
      context: ./../staff-service
      dockerfile: ./../staff-service/staff.dockerfile
    restart: always
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
      AUTH_SERVICE: "authentication-service:50001"
      INSTITUTION_SERVICE: "institution-service:50002"
      BASE_PATH: "/staff-services-host"
  appointment-service:
      build:
        context: ./../appointment-service
        dockerfile: ./../appointment-service/appointments.dockerfile
      restart: always
      ports:
        - "8083:8083"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
        AUTH_SERVICE: "authentication-service:50001"
        STAFF_SERVICE_HOST_WITHSLASHATTHEEND: "staff-service/"
        RABBITMQ_HOST: "amqp://guest:guest@rabbitmq"
        BASE_PATH: "/appointment-service"

  notification-service:
      build:
        context: ./../notification-service
        dockerfile: ./../notification-service/notification.dockerfile
      restart: always
      ports:
        - "8084:8084"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
        host: "https://sendnotification-4nnknk7h2a-uc.a.run.app"
        RABBITMQ_HOST: "amqp://guest:guest@rabbitmq"

  queue-service:
      build:
        context: ./../queue-management-service
        dockerfile: ./../queue-management-service/queue.dockerfile
      restart: always
      ports:
        - "8087:8087"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        DSN: "host=postgres port=5432 user=postgres password=190704Samat dbname=reserveHub sslmode=disable timezone=UTC connect_timeout=5"
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        staff_service_host: "staff-service:8082/staff-services-host/"
        AUTH_SERVICE: "authentication-service:50001"
        RABBITMQ_HOST: "amqp://guest:guest@rabbitmq"
        BASE_PATH: "/queue-service"


  postgres:
    image: 'postgres:alpine3.18'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190704Samat
      POSTGRES_DB: reserveHub
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  rabbitmq:
      image: 'rabbitmq:3.9-alpine'
      ports:
        - "5672:5672"
      deploy:
        mode: replicated
        replicas: 1
      volumes:
        - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  redis:
    image: 'redis:7.0-alpine'
    ports:
      - "6379:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/redis/:/data/



# aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  982796488014.dkr.ecr.us-east-1.amazonaws.com

# docker tag project-broker-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-1-broker-with-hit
# docker tag project-authentication-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-2
# docker tag project-institution-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:institution-service
# docker tag project-staff-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:staff-service
# docker tag project-appointment-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:appointment-service
# docker tag project-notification-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:notification-service
# docker tag project-queue-service 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:queue-service

# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-1-broker-with-hit
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:institution-service
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:staff-service
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:appointment-service
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:notification-service
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:queue-service
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-9
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-10

# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-2
# docker push 982796488014.dkr.ecr.us-east-1.amazonaws.com/reserve-hub:latest-3