// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: employee_proto.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenEmployeeRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId       int64 `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	InstitutionId int64 `protobuf:"varint,2,opt,name=institutionId,proto3" json:"institutionId,omitempty"`
}

func (x *TokenEmployeeRegisterRequest) Reset() {
	*x = TokenEmployeeRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenEmployeeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEmployeeRegisterRequest) ProtoMessage() {}

func (x *TokenEmployeeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEmployeeRegisterRequest.ProtoReflect.Descriptor instead.
func (*TokenEmployeeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_proto_rawDescGZIP(), []int{0}
}

func (x *TokenEmployeeRegisterRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *TokenEmployeeRegisterRequest) GetInstitutionId() int64 {
	if x != nil {
		return x.InstitutionId
	}
	return 0
}

type TokenEmployeeRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TokenEmployeeRegisterResponse) Reset() {
	*x = TokenEmployeeRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_employee_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenEmployeeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEmployeeRegisterResponse) ProtoMessage() {}

func (x *TokenEmployeeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEmployeeRegisterResponse.ProtoReflect.Descriptor instead.
func (*TokenEmployeeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_proto_rawDescGZIP(), []int{1}
}

func (x *TokenEmployeeRegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenEmployeeRegisterResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_employee_proto_proto protoreflect.FileDescriptor

var file_employee_proto_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x22, 0x5e, 0x0a, 0x1c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e,
	0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x4d, 0x0a, 0x1d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x83, 0x01, 0x0a, 0x1c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x63, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x12, 0x26, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_employee_proto_proto_rawDescOnce sync.Once
	file_employee_proto_proto_rawDescData = file_employee_proto_proto_rawDesc
)

func file_employee_proto_proto_rawDescGZIP() []byte {
	file_employee_proto_proto_rawDescOnce.Do(func() {
		file_employee_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_employee_proto_proto_rawDescData)
	})
	return file_employee_proto_proto_rawDescData
}

var file_employee_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_proto_proto_goTypes = []interface{}{
	(*TokenEmployeeRegisterRequest)(nil),  // 0: employee.TokenEmployeeRegisterRequest
	(*TokenEmployeeRegisterResponse)(nil), // 1: employee.TokenEmployeeRegisterResponse
}
var file_employee_proto_proto_depIdxs = []int32{
	0, // 0: employee.TokenEmployeeRegisterService.RegisterEmployee:input_type -> employee.TokenEmployeeRegisterRequest
	1, // 1: employee.TokenEmployeeRegisterService.RegisterEmployee:output_type -> employee.TokenEmployeeRegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_employee_proto_proto_init() }
func file_employee_proto_proto_init() {
	if File_employee_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_employee_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenEmployeeRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_employee_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenEmployeeRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_employee_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_proto_proto_goTypes,
		DependencyIndexes: file_employee_proto_proto_depIdxs,
		MessageInfos:      file_employee_proto_proto_msgTypes,
	}.Build()
	File_employee_proto_proto = out.File
	file_employee_proto_proto_rawDesc = nil
	file_employee_proto_proto_goTypes = nil
	file_employee_proto_proto_depIdxs = nil
}
